name: CD

on:
  release:
    types:
      - created
  workflow_dispatch:
  # pull_request:
  # uncomment the above to test CD in a PR

jobs:
  build-gpu:
    name: Build GPU Image
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx        
      uses: docker/setup-buildx-action@v2
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }}-gpu
        platforms: linux/amd64


  build-cpu:
    name: Build CPU Image
    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU        
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx        
      uses: docker/setup-buildx-action@v2

    - name: Docker Login
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }}
        platforms: linux/amd64,linux/arm64