name: CD

on:
  push:
    branches:
      - $default-branch
  workflow_dispatch:
#  pull_request:
# uncoment the line above to test CD push in a PR

jobs:
  push-executors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: push to Hubble
        run: |
          bash ./.github/workflows/scripts/push.sh .
        env:
          token: ${{ secrets.GH_TOKEN }}
          GIT_TAG: ${{ steps.previoustag.outputs.tag }}
